apiVersion: v1
kind: Pod
metadata :
  name: pod3
  labels:
    app: helloworld
spec:
  containers:
  - name: sg8-test1
    image: arjunachari12/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
